#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TipCalc.Droid.Resource", IsApplication=true)]

namespace TipCalc.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Resource.Attribute.MvxBind = global::TipCalc.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Resource.Attribute.MvxDropDownItemTemplate = global::TipCalc.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxGroupItemTemplate = global::TipCalc.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxItemTemplate = global::TipCalc.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxLang = global::TipCalc.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Resource.Attribute.MvxTemplate = global::TipCalc.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Resource.Id.MvvmCrossTagId = global::TipCalc.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Resource.Id.MvxBindingTagUnique = global::TipCalc.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Resource.Styleable.MvxBinding = global::TipCalc.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Resource.Styleable.MvxBinding_MvxBind = global::TipCalc.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Resource.Styleable.MvxBinding_MvxLang = global::TipCalc.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Resource.Styleable.MvxControl = global::TipCalc.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Resource.Styleable.MvxControl_MvxTemplate = global::TipCalc.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Resource.Styleable.MvxExpandableListView = global::TipCalc.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TipCalc.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Resource.Styleable.MvxListView = global::TipCalc.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TipCalc.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Resource.Styleable.MvxListView_MvxItemTemplate = global::TipCalc.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.alpha = global::TipCalc.Droid.Resource.Attribute.alpha;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.coordinatorLayoutStyle = global::TipCalc.Droid.Resource.Attribute.coordinatorLayoutStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollEnabled = global::TipCalc.Droid.Resource.Attribute.fastScrollEnabled;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollHorizontalThumbDrawable = global::TipCalc.Droid.Resource.Attribute.fastScrollHorizontalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollHorizontalTrackDrawable = global::TipCalc.Droid.Resource.Attribute.fastScrollHorizontalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollVerticalThumbDrawable = global::TipCalc.Droid.Resource.Attribute.fastScrollVerticalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollVerticalTrackDrawable = global::TipCalc.Droid.Resource.Attribute.fastScrollVerticalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.font = global::TipCalc.Droid.Resource.Attribute.font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderAuthority = global::TipCalc.Droid.Resource.Attribute.fontProviderAuthority;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderCerts = global::TipCalc.Droid.Resource.Attribute.fontProviderCerts;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderFetchStrategy = global::TipCalc.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderFetchTimeout = global::TipCalc.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderPackage = global::TipCalc.Droid.Resource.Attribute.fontProviderPackage;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderQuery = global::TipCalc.Droid.Resource.Attribute.fontProviderQuery;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontStyle = global::TipCalc.Droid.Resource.Attribute.fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontVariationSettings = global::TipCalc.Droid.Resource.Attribute.fontVariationSettings;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontWeight = global::TipCalc.Droid.Resource.Attribute.fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.keylines = global::TipCalc.Droid.Resource.Attribute.keylines;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layoutManager = global::TipCalc.Droid.Resource.Attribute.layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layout_anchor = global::TipCalc.Droid.Resource.Attribute.layout_anchor;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layout_anchorGravity = global::TipCalc.Droid.Resource.Attribute.layout_anchorGravity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layout_behavior = global::TipCalc.Droid.Resource.Attribute.layout_behavior;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layout_dodgeInsetEdges = global::TipCalc.Droid.Resource.Attribute.layout_dodgeInsetEdges;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layout_insetEdge = global::TipCalc.Droid.Resource.Attribute.layout_insetEdge;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layout_keyline = global::TipCalc.Droid.Resource.Attribute.layout_keyline;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxBind = global::TipCalc.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxDropDownItemTemplate = global::TipCalc.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxGroupItemTemplate = global::TipCalc.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxItemTemplate = global::TipCalc.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxLang = global::TipCalc.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplate = global::TipCalc.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplateSelector = global::TipCalc.Droid.Resource.Attribute.MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.reverseLayout = global::TipCalc.Droid.Resource.Attribute.reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.spanCount = global::TipCalc.Droid.Resource.Attribute.spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.stackFromEnd = global::TipCalc.Droid.Resource.Attribute.stackFromEnd;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.statusBarBackground = global::TipCalc.Droid.Resource.Attribute.statusBarBackground;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.ttcIndex = global::TipCalc.Droid.Resource.Attribute.ttcIndex;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.notification_action_color_filter = global::TipCalc.Droid.Resource.Color.notification_action_color_filter;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.notification_icon_bg_color = global::TipCalc.Droid.Resource.Color.notification_icon_bg_color;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.ripple_material_light = global::TipCalc.Droid.Resource.Color.ripple_material_light;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.secondary_text_default_material_light = global::TipCalc.Droid.Resource.Color.secondary_text_default_material_light;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_inset_horizontal_material = global::TipCalc.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_inset_vertical_material = global::TipCalc.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_padding_horizontal_material = global::TipCalc.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_padding_vertical_material = global::TipCalc.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_control_corner_material = global::TipCalc.Droid.Resource.Dimension.compat_control_corner_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_notification_large_icon_max_height = global::TipCalc.Droid.Resource.Dimension.compat_notification_large_icon_max_height;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_notification_large_icon_max_width = global::TipCalc.Droid.Resource.Dimension.compat_notification_large_icon_max_width;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_default_thickness = global::TipCalc.Droid.Resource.Dimension.fastscroll_default_thickness;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_margin = global::TipCalc.Droid.Resource.Dimension.fastscroll_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_minimum_range = global::TipCalc.Droid.Resource.Dimension.fastscroll_minimum_range;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::TipCalc.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::TipCalc.Droid.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::TipCalc.Droid.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_action_icon_size = global::TipCalc.Droid.Resource.Dimension.notification_action_icon_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_action_text_size = global::TipCalc.Droid.Resource.Dimension.notification_action_text_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_big_circle_margin = global::TipCalc.Droid.Resource.Dimension.notification_big_circle_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_content_margin_start = global::TipCalc.Droid.Resource.Dimension.notification_content_margin_start;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_large_icon_height = global::TipCalc.Droid.Resource.Dimension.notification_large_icon_height;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_large_icon_width = global::TipCalc.Droid.Resource.Dimension.notification_large_icon_width;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_main_column_padding_top = global::TipCalc.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_media_narrow_margin = global::TipCalc.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_right_icon_size = global::TipCalc.Droid.Resource.Dimension.notification_right_icon_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_right_side_padding_top = global::TipCalc.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_small_icon_background_padding = global::TipCalc.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_small_icon_size_as_large = global::TipCalc.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_subtext_size = global::TipCalc.Droid.Resource.Dimension.notification_subtext_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_top_pad = global::TipCalc.Droid.Resource.Dimension.notification_top_pad;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_top_pad_large_text = global::TipCalc.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_action_background = global::TipCalc.Droid.Resource.Drawable.notification_action_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg = global::TipCalc.Droid.Resource.Drawable.notification_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low = global::TipCalc.Droid.Resource.Drawable.notification_bg_low;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low_normal = global::TipCalc.Droid.Resource.Drawable.notification_bg_low_normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low_pressed = global::TipCalc.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_normal = global::TipCalc.Droid.Resource.Drawable.notification_bg_normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_normal_pressed = global::TipCalc.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_icon_background = global::TipCalc.Droid.Resource.Drawable.notification_icon_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_template_icon_bg = global::TipCalc.Droid.Resource.Drawable.notification_template_icon_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_template_icon_low_bg = global::TipCalc.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_tile_bg = global::TipCalc.Droid.Resource.Drawable.notification_tile_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notify_panel_notification_icon_bg = global::TipCalc.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.actions = global::TipCalc.Droid.Resource.Id.actions;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_container = global::TipCalc.Droid.Resource.Id.action_container;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_divider = global::TipCalc.Droid.Resource.Id.action_divider;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_image = global::TipCalc.Droid.Resource.Id.action_image;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_text = global::TipCalc.Droid.Resource.Id.action_text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.all = global::TipCalc.Droid.Resource.Id.all;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.async = global::TipCalc.Droid.Resource.Id.async;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.blocking = global::TipCalc.Droid.Resource.Id.blocking;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.bottom = global::TipCalc.Droid.Resource.Id.bottom;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.center = global::TipCalc.Droid.Resource.Id.center;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.center_horizontal = global::TipCalc.Droid.Resource.Id.center_horizontal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.center_vertical = global::TipCalc.Droid.Resource.Id.center_vertical;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.chronometer = global::TipCalc.Droid.Resource.Id.chronometer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.clip_horizontal = global::TipCalc.Droid.Resource.Id.clip_horizontal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.clip_vertical = global::TipCalc.Droid.Resource.Id.clip_vertical;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.end = global::TipCalc.Droid.Resource.Id.end;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.fill = global::TipCalc.Droid.Resource.Id.fill;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.fill_horizontal = global::TipCalc.Droid.Resource.Id.fill_horizontal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.fill_vertical = global::TipCalc.Droid.Resource.Id.fill_vertical;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.forever = global::TipCalc.Droid.Resource.Id.forever;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.icon = global::TipCalc.Droid.Resource.Id.icon;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.icon_group = global::TipCalc.Droid.Resource.Id.icon_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.info = global::TipCalc.Droid.Resource.Id.info;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.italic = global::TipCalc.Droid.Resource.Id.italic;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.item_touch_helper_previous_elevation = global::TipCalc.Droid.Resource.Id.item_touch_helper_previous_elevation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.left = global::TipCalc.Droid.Resource.Id.left;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.line1 = global::TipCalc.Droid.Resource.Id.line1;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.line3 = global::TipCalc.Droid.Resource.Id.line3;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvvmCrossTagId = global::TipCalc.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvxBindingTagUnique = global::TipCalc.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.none = global::TipCalc.Droid.Resource.Id.none;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.normal = global::TipCalc.Droid.Resource.Id.normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_background = global::TipCalc.Droid.Resource.Id.notification_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_main_column = global::TipCalc.Droid.Resource.Id.notification_main_column;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_main_column_container = global::TipCalc.Droid.Resource.Id.notification_main_column_container;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.right = global::TipCalc.Droid.Resource.Id.right;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.right_icon = global::TipCalc.Droid.Resource.Id.right_icon;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.right_side = global::TipCalc.Droid.Resource.Id.right_side;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.start = global::TipCalc.Droid.Resource.Id.start;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.tag_transition_group = global::TipCalc.Droid.Resource.Id.tag_transition_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.tag_unhandled_key_event_manager = global::TipCalc.Droid.Resource.Id.tag_unhandled_key_event_manager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.tag_unhandled_key_listeners = global::TipCalc.Droid.Resource.Id.tag_unhandled_key_listeners;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.text = global::TipCalc.Droid.Resource.Id.text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.text2 = global::TipCalc.Droid.Resource.Id.text2;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.time = global::TipCalc.Droid.Resource.Id.time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.title = global::TipCalc.Droid.Resource.Id.title;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.top = global::TipCalc.Droid.Resource.Id.top;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Integer.status_bar_notification_info_maxnum = global::TipCalc.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_action = global::TipCalc.Droid.Resource.Layout.notification_action;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_action_tombstone = global::TipCalc.Droid.Resource.Layout.notification_action_tombstone;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_custom_big = global::TipCalc.Droid.Resource.Layout.notification_template_custom_big;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_icon_group = global::TipCalc.Droid.Resource.Layout.notification_template_icon_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_part_chronometer = global::TipCalc.Droid.Resource.Layout.notification_template_part_chronometer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_part_time = global::TipCalc.Droid.Resource.Layout.notification_template_part_time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.String.status_bar_notification_info_overflow = global::TipCalc.Droid.Resource.String.status_bar_notification_info_overflow;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Info = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Time = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Title = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.Widget_Compat_NotificationActionContainer = global::TipCalc.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.Widget_Compat_NotificationActionText = global::TipCalc.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.Widget_Support_CoordinatorLayout = global::TipCalc.Droid.Resource.Style.Widget_Support_CoordinatorLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.ColorStateListItem = global::TipCalc.Droid.Resource.Styleable.ColorStateListItem;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.ColorStateListItem_alpha = global::TipCalc.Droid.Resource.Styleable.ColorStateListItem_alpha;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.ColorStateListItem_android_alpha = global::TipCalc.Droid.Resource.Styleable.ColorStateListItem_android_alpha;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.ColorStateListItem_android_color = global::TipCalc.Droid.Resource.Styleable.ColorStateListItem_android_color;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_keylines = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_keylines;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_Layout = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily = global::TipCalc.Droid.Resource.Styleable.FontFamily;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_font = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_fontStyle = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_fontWeight = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_font = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_fontStyle = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_fontWeight = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_ttcIndex = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderAuthority = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderCerts = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderPackage = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderQuery = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor = global::TipCalc.Droid.Resource.Styleable.GradientColor;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColorItem = global::TipCalc.Droid.Resource.Styleable.GradientColorItem;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColorItem_android_color = global::TipCalc.Droid.Resource.Styleable.GradientColorItem_android_color;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColorItem_android_offset = global::TipCalc.Droid.Resource.Styleable.GradientColorItem_android_offset;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_centerColor = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_centerColor;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_centerX = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_centerX;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_centerY = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_centerY;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_endColor = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_endColor;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_endX = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_endX;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_endY = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_endY;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_gradientRadius = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_gradientRadius;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_startColor = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_startColor;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_startX = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_startX;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_startY = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_startY;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_tileMode = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_tileMode;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.GradientColor_android_type = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_type;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding = global::TipCalc.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxBind = global::TipCalc.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxLang = global::TipCalc.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl = global::TipCalc.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl_MvxTemplate = global::TipCalc.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView = global::TipCalc.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TipCalc.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView = global::TipCalc.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TipCalc.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxItemTemplate = global::TipCalc.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView = global::TipCalc.Droid.Resource.Styleable.MvxRecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector = global::TipCalc.Droid.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView = global::TipCalc.Droid.Resource.Styleable.RecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_descendantFocusability = global::TipCalc.Droid.Resource.Styleable.RecyclerView_android_descendantFocusability;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_orientation = global::TipCalc.Droid.Resource.Styleable.RecyclerView_android_orientation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollEnabled = global::TipCalc.Droid.Resource.Styleable.RecyclerView_fastScrollEnabled;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollHorizontalThumbDrawable = global::TipCalc.Droid.Resource.Styleable.RecyclerView_fastScrollHorizontalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollHorizontalTrackDrawable = global::TipCalc.Droid.Resource.Styleable.RecyclerView_fastScrollHorizontalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollVerticalThumbDrawable = global::TipCalc.Droid.Resource.Styleable.RecyclerView_fastScrollVerticalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollVerticalTrackDrawable = global::TipCalc.Droid.Resource.Styleable.RecyclerView_fastScrollVerticalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_layoutManager = global::TipCalc.Droid.Resource.Styleable.RecyclerView_layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_reverseLayout = global::TipCalc.Droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_spanCount = global::TipCalc.Droid.Resource.Styleable.RecyclerView_spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_stackFromEnd = global::TipCalc.Droid.Resource.Styleable.RecyclerView_stackFromEnd;
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::TipCalc.Droid.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.coordinatorLayoutStyle = global::TipCalc.Droid.Resource.Attribute.coordinatorLayoutStyle;
			global::Xamarin.Essentials.Resource.Attribute.font = global::TipCalc.Droid.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::TipCalc.Droid.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::TipCalc.Droid.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::TipCalc.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::TipCalc.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::TipCalc.Droid.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::TipCalc.Droid.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::TipCalc.Droid.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::TipCalc.Droid.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::TipCalc.Droid.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.keylines = global::TipCalc.Droid.Resource.Attribute.keylines;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchor = global::TipCalc.Droid.Resource.Attribute.layout_anchor;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchorGravity = global::TipCalc.Droid.Resource.Attribute.layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Attribute.layout_behavior = global::TipCalc.Droid.Resource.Attribute.layout_behavior;
			global::Xamarin.Essentials.Resource.Attribute.layout_dodgeInsetEdges = global::TipCalc.Droid.Resource.Attribute.layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Attribute.layout_insetEdge = global::TipCalc.Droid.Resource.Attribute.layout_insetEdge;
			global::Xamarin.Essentials.Resource.Attribute.layout_keyline = global::TipCalc.Droid.Resource.Attribute.layout_keyline;
			global::Xamarin.Essentials.Resource.Attribute.statusBarBackground = global::TipCalc.Droid.Resource.Attribute.statusBarBackground;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::TipCalc.Droid.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::TipCalc.Droid.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::TipCalc.Droid.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::TipCalc.Droid.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::TipCalc.Droid.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::TipCalc.Droid.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::TipCalc.Droid.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::TipCalc.Droid.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::TipCalc.Droid.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::TipCalc.Droid.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::TipCalc.Droid.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::TipCalc.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::TipCalc.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::TipCalc.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::TipCalc.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::TipCalc.Droid.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::TipCalc.Droid.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::TipCalc.Droid.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::TipCalc.Droid.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::TipCalc.Droid.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::TipCalc.Droid.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::TipCalc.Droid.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::TipCalc.Droid.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::TipCalc.Droid.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::TipCalc.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::TipCalc.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::TipCalc.Droid.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::TipCalc.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::TipCalc.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::TipCalc.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::TipCalc.Droid.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::TipCalc.Droid.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::TipCalc.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::TipCalc.Droid.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::TipCalc.Droid.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::TipCalc.Droid.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::TipCalc.Droid.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::TipCalc.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::TipCalc.Droid.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::TipCalc.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::TipCalc.Droid.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::TipCalc.Droid.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::TipCalc.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::TipCalc.Droid.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::TipCalc.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.actions = global::TipCalc.Droid.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.action_container = global::TipCalc.Droid.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::TipCalc.Droid.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::TipCalc.Droid.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::TipCalc.Droid.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.all = global::TipCalc.Droid.Resource.Id.all;
			global::Xamarin.Essentials.Resource.Id.async = global::TipCalc.Droid.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::TipCalc.Droid.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.bottom = global::TipCalc.Droid.Resource.Id.bottom;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::TipCalc.Droid.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::TipCalc.Droid.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::TipCalc.Droid.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::TipCalc.Droid.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::TipCalc.Droid.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.center = global::TipCalc.Droid.Resource.Id.center;
			global::Xamarin.Essentials.Resource.Id.center_horizontal = global::TipCalc.Droid.Resource.Id.center_horizontal;
			global::Xamarin.Essentials.Resource.Id.center_vertical = global::TipCalc.Droid.Resource.Id.center_vertical;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::TipCalc.Droid.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.clip_horizontal = global::TipCalc.Droid.Resource.Id.clip_horizontal;
			global::Xamarin.Essentials.Resource.Id.clip_vertical = global::TipCalc.Droid.Resource.Id.clip_vertical;
			global::Xamarin.Essentials.Resource.Id.end = global::TipCalc.Droid.Resource.Id.end;
			global::Xamarin.Essentials.Resource.Id.fill = global::TipCalc.Droid.Resource.Id.fill;
			global::Xamarin.Essentials.Resource.Id.fill_horizontal = global::TipCalc.Droid.Resource.Id.fill_horizontal;
			global::Xamarin.Essentials.Resource.Id.fill_vertical = global::TipCalc.Droid.Resource.Id.fill_vertical;
			global::Xamarin.Essentials.Resource.Id.forever = global::TipCalc.Droid.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::TipCalc.Droid.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::TipCalc.Droid.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::TipCalc.Droid.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::TipCalc.Droid.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.left = global::TipCalc.Droid.Resource.Id.left;
			global::Xamarin.Essentials.Resource.Id.line1 = global::TipCalc.Droid.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::TipCalc.Droid.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.none = global::TipCalc.Droid.Resource.Id.none;
			global::Xamarin.Essentials.Resource.Id.normal = global::TipCalc.Droid.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::TipCalc.Droid.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::TipCalc.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::TipCalc.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right = global::TipCalc.Droid.Resource.Id.right;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::TipCalc.Droid.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::TipCalc.Droid.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.start = global::TipCalc.Droid.Resource.Id.start;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::TipCalc.Droid.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::TipCalc.Droid.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::TipCalc.Droid.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::TipCalc.Droid.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::TipCalc.Droid.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::TipCalc.Droid.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::TipCalc.Droid.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Id.top = global::TipCalc.Droid.Resource.Id.top;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::TipCalc.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::TipCalc.Droid.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::TipCalc.Droid.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::TipCalc.Droid.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::TipCalc.Droid.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::TipCalc.Droid.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::TipCalc.Droid.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::TipCalc.Droid.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::TipCalc.Droid.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::TipCalc.Droid.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::TipCalc.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::TipCalc.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::TipCalc.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Style.Widget_Support_CoordinatorLayout = global::TipCalc.Droid.Resource.Style.Widget_Support_CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::TipCalc.Droid.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::TipCalc.Droid.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::TipCalc.Droid.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::TipCalc.Droid.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_keylines = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_keylines;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::TipCalc.Droid.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::TipCalc.Droid.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::TipCalc.Droid.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::TipCalc.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::TipCalc.Droid.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::TipCalc.Droid.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::TipCalc.Droid.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::TipCalc.Droid.Resource.Styleable.GradientColorItem_android_offset;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::TipCalc.Droid.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::TipCalc.Droid.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010007
			public const int alpha = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int coordinatorLayoutStyle = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fastScrollEnabled = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fastScrollHorizontalThumbDrawable = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fastScrollHorizontalTrackDrawable = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int fastScrollVerticalThumbDrawable = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int fastScrollVerticalTrackDrawable = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int font = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int fontProviderAuthority = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int fontProviderCerts = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int fontProviderFetchStrategy = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int fontProviderFetchTimeout = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int fontProviderPackage = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int fontProviderQuery = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int fontStyle = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int fontVariationSettings = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int fontWeight = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int keylines = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int layoutManager = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int layout_anchor = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int layout_anchorGravity = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int layout_behavior = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int layout_dodgeInsetEdges = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int layout_insetEdge = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int layout_keyline = 2130771999;
			
			// aapt resource value: 0x7F010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int MvxDropDownItemTemplate = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int MvxGroupItemTemplate = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int MvxLang = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int MvxTemplate = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int MvxTemplateSelector = 2130771974;
			
			// aapt resource value: 0x7F010020
			public const int reverseLayout = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int spanCount = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int stackFromEnd = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int statusBarBackground = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int ttcIndex = 2130772004;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int browser_actions_bg_grey = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int browser_actions_divider_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int browser_actions_text_color = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int browser_actions_title_color = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int colorAccent = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int colorPrimary = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int colorPrimaryDark = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int ic_launcher_background = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int notification_action_color_filter = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int notification_icon_bg_color = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int ripple_material_light = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int secondary_text_default_material_light = 2130837515;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int browser_actions_context_menu_max_width = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int browser_actions_context_menu_min_padding = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int compat_button_inset_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_inset_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_button_padding_horizontal_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_button_padding_vertical_material = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_control_corner_material = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int compat_notification_large_icon_max_height = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int compat_notification_large_icon_max_width = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int fastscroll_default_thickness = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int fastscroll_margin = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int fastscroll_minimum_range = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int item_touch_helper_swipe_escape_max_velocity = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int item_touch_helper_swipe_escape_velocity = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int notification_action_icon_size = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_action_text_size = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_big_circle_margin = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_content_margin_start = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_large_icon_height = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_large_icon_width = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_main_column_padding_top = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int notification_media_narrow_margin = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int notification_right_icon_size = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int notification_right_side_padding_top = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int notification_small_icon_background_padding = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int notification_small_icon_size_as_large = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int notification_subtext_size = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int notification_top_pad = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int notification_top_pad_large_text = 2130903069;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int notification_action_background = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int notification_bg = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int notification_bg_low = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int notification_bg_low_normal = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int notification_bg_low_pressed = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_bg_normal = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_bg_normal_pressed = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_icon_background = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_template_icon_bg = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_template_icon_low_bg = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_tile_bg = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notify_panel_notification_icon_bg = 2130968587;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050006
			public const int actions = 2131034118;
			
			// aapt resource value: 0x7F050002
			public const int action_container = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int action_divider = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int action_image = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int action_text = 2131034117;
			
			// aapt resource value: 0x7F050007
			public const int all = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int async = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int blocking = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int bottom = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int browser_actions_header_text = 2131034123;
			
			// aapt resource value: 0x7F05000E
			public const int browser_actions_menu_items = 2131034126;
			
			// aapt resource value: 0x7F05000C
			public const int browser_actions_menu_item_icon = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int browser_actions_menu_item_text = 2131034125;
			
			// aapt resource value: 0x7F05000F
			public const int browser_actions_menu_view = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int button = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int center = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int center_horizontal = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int center_vertical = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int chronometer = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int clip_horizontal = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int clip_vertical = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int end = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int fill = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int fill_horizontal = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int fill_vertical = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int forever = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int icon = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int icon_group = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int info = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int italic = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int item_touch_helper_previous_elevation = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int left = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int line1 = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int line3 = 2131034147;
			
			// aapt resource value: 0x7F050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7F050024
			public const int none = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int normal = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int notification_background = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int notification_main_column = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int notification_main_column_container = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int right = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int right_icon = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int right_side = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int start = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int tag_transition_group = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int tag_unhandled_key_event_manager = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int tag_unhandled_key_listeners = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int text = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int text2 = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int time = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int title = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int top = 2131034164;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int status_bar_notification_info_maxnum = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int browser_actions_context_menu_page = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int browser_actions_context_menu_row = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int notification_action = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int notification_action_tombstone = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int notification_template_custom_big = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_template_icon_group = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_template_part_chronometer = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_template_part_time = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int SecondView = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int TipView = 2131165193;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F080000
			public const int ic_launcher = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int ic_launcher_foreground = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int ic_launcher_round = 2131230722;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int action_settings = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int status_bar_notification_info_overflow = 2131296258;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TextAppearance_Compat_Notification = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int TextAppearance_Compat_Notification_Info = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int TextAppearance_Compat_Notification_Line2 = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int TextAppearance_Compat_Notification_Time = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int TextAppearance_Compat_Notification_Title = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int Widget_Compat_NotificationActionContainer = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int Widget_Compat_NotificationActionText = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int Widget_Support_CoordinatorLayout = 2131361800;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010007 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771975};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F010018,0x7F010023 }
			public static int[] CoordinatorLayout = new int[] {
					2130771992,
					2130772003};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F01001A,0x7F01001B,0x7F01001C,0x7F01001D,0x7F01001E,0x7F01001F }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F01000F,0x7F010010,0x7F010011,0x7F010012,0x7F010013,0x7F010014 }
			public static int[] FontFamily = new int[] {
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F01000E,0x7F010015,0x7F010016,0x7F010017,0x7F010024 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771982,
					2130771989,
					2130771990,
					2130771991,
					2130772004};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F010000,0x7F010004 }
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771972};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			// aapt resource value: { 0x7F010005 }
			public static int[] MvxControl = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			// aapt resource value: { 0x7F010002 }
			public static int[] MvxExpandableListView = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			// aapt resource value: { 0x7F010001,0x7F010003 }
			public static int[] MvxListView = new int[] {
					2130771969,
					2130771971};
			
			// aapt resource value: 0
			public const int MvxListView_MvxDropDownItemTemplate = 0;
			
			// aapt resource value: 1
			public const int MvxListView_MvxItemTemplate = 1;
			
			// aapt resource value: { 0x7F010006 }
			public static int[] MvxRecyclerView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxRecyclerView_MvxTemplateSelector = 0;
			
			// aapt resource value: { 0x10100C4,0x10100F1,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F010019,0x7F010020,0x7F010021,0x7F010022 }
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771993,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_fastScrollEnabled = 2;
			
			// aapt resource value: 3
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 3;
			
			// aapt resource value: 4
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 4;
			
			// aapt resource value: 5
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 5;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 6;
			
			// aapt resource value: 7
			public const int RecyclerView_layoutManager = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_reverseLayout = 8;
			
			// aapt resource value: 9
			public const int RecyclerView_spanCount = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_stackFromEnd = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0C0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131492864;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
